import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "화장실 찾기",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="w-full">{children}</main>
      </body>
    </html>
  );
}
